FROM python:3.10-slim-buster

WORKDIR /backend

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY ./requirements/requirements.txt /backend/requirements/requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements/requirements.txt

COPY ./app .

RUN python manage.py makemigrations
