
  name: Frontend
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    Temp:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 14
        
        - name: Install dependecies
          run: npm ci
        
        - name: Run ESLine
          run: npm run lint
          working-directory: ./frontend
        
        
